import type { Metadata } from "next";
import "../styles/globals.scss";
import Providers from "../layout/providers";
import { CONFIG } from "../config/config";

export const metadata: Metadata = {
  title: CONFIG.APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
